### ISSUE TITLE
Migrate to SPA using Vue

### ISSUE THREAD

**Issue by nimitbhargava** [gcdcblr/gcdcblr.in#34]
This is a proposal to move the project to SPA using Vus.js
I can create PR for this if that's okay?

**Comment by roommen** [comment]
Not reqd for now and I personally don't encourage meaningless contributions like this in Oct just because a competition is going to earn T-shirts and stickers by submitting anything #shitoberfest

**Comment by nimitbhargava** [comment]
@roommen I proposed and not created a PR right away. 
Also, I don't see this as meaningless contribution. It's a great way for someone to learn to migrate their web apps to Vue.js. 

Anyway, I appreciate your feedback on it and you maintaining the repo.
And definitely stand again spammy PRs during October.

**Comment by roommen** [comment]
For learning feel free to fork and see for yourself; that's what git is for :)
